### ISSUE TITLE
Request: Multi-GPU support.

### ISSUE THREAD

**Issue by Draqen4** [CardinalPanda/dandere2x#17]
Would it be possible to enable the software to make use of systems that have multiple GPU's / SLI setups?
In the past i've split my video's frames into two bins, then set 2 copies of Waifu2x-caffe going, with each set to render on each seperate GPU. (I have 2 GPUs)

I found there's a fairly straightforward way to do it. waifu2x-caffe-cui.exe just needs the --gpu argument followed by which GPU to use, starting with 0. So a system with 2 graphics cards would have one copy going with the "--gpu 0" argument, and another instance with "--gpu 1"

If you could possibly add this it'd be much appreciated :D. keep up the awesome work!

**Comment by CardinalPanda** [comment]
definitely, it would be easy to add.

**Comment by CardinalPanda** [comment]
on development branch right now. Let me know if you want me to compile a release for it!

**Comment by Draqen4** [comment]
That'd be awesome if you can so I can test it <3. I've no idea how to compile it myself from the source hehe.
