### ISSUE TITLE
Give instructions on how to build

### ISSUE THREAD

**Issue by aviallon** [CardinalPanda/dandere2x#6]
Hello, I think you should really consider taking the time to clean up your mess for building, perhaps use cmake to allow platform independent build file, and perhaps provide a documentation on how to use it. If you do, I may be able to help you do your project, and other people might also help.

Have a nice evening !
Antoine Viallon

**Comment by CardinalPanda** [comment]
hello,

I release ready-to-go builds on https://www.reddit.com/r/Dandere2x/ for testers, however...

Now that you mention it / are interested, I plan on writing how to build! I haven't gotten around to it so far, as the project has remained relatively small. 

I'm excited that you want to help out, and I plan on making my code more accessible to others. Thanks for letting me know!

**Comment by CardinalPanda** [comment]
Added cmake!

**Comment by aviallon** [comment]
Yahoo!
